#!/bin/sh
exec tail -n +3 $0

# custom menu entry
menuentry 'Gentoo GNU/Linux (AUTO-UPDATE)' --class gentoo --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-auto-update-b8380f3f-c5bd-41cd-9c22-7dd5505c7b77' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod xfs
        search --no-floppy --fs-uuid --set=root e939d07c-7a1e-404c-a2d1-b33302600cf9 
        echo    'Loading Linux x.x.x-gentoo-dist-bin ...'
        linux   /boot/vmlinuz-x.x.x-gentoo-dist-bin root=UUID=e939d07c-7a1e-404c-a2d1-b33302600cf9 ro -auto_update
        echo    'Loading initial ramdisk ...'
        initrd  /boot/initramfs-x.x.x-gentoo-dist-bin.img
}
